<table>
	<tr>
		<td><h2><?php echo $this->__("Introduciendo...") ?></h2></td>
		<td>&nbsp;</td>
		<td><img src='<?php echo $this->getSkinUrl('images/payment4b/mastercard_secuercode.png') ?>' width='116' /></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("MasterCard SecureCode TM es un nuevo servicio de MasterCard y de su emisor de tarjeta que proporciona proteccion adicional cuando usted realiza compras online."); ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr><td colspan='3'><?php echo $this->__("No hay necesidad de obtener una nueva tarjeta MasterCard o Maestro. Usted escoge su propio MasterCard SecureCode personal y &eacute;ste nunca es compartido con ning&uacute;n comercio. "); ?></td></tr>

	<tr><td colspan="3"><?php echo $this->__("Un c&oacute;digo privado significa protecci&oacute;n adicional contra el uso no autorizado de su tarjeta de cr&eacute;dito y de d&eacute;bito cuando usted compre online.") ?><td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Cada vez que pague online con su tarjeta MasterCard o Maestro, una ventana que proviene de su emisor de tarjeta se abre pregunt&aacute;ndole por su SecureCode personal, tal como su banco le pregunta en el cajero autom&aacute;tico.'); ?></td></tr>
<tr><td colspan='3'><?php echo $this->__('En segundos, su emisor de tarjeta confirma que es usted y le permite completar su compra.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td><img src='<?php echo $this->getSkinUrl('images/payment4b/mastercard.png') ?>' width='72' /></td>
		<td><?php echo $this->__('Para obtener m&aacute;s informaci&oacute;n sobre MasterCard SecureCode dir&iacute;jase a <a href="http://www.mastercardsecurecode.com">www.mastercardsecurecode.com</a>') ?></td>
		<td><img src='<?php echo $this->getSkinUrl('images/payment4b/maestro.png') ?>' width='72' /></td>
	</tr>
	<tr>
		<td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->helper('page')->__('Close Window')?></button></td>
	</tr>
</table>
