<script type="text/javascript" src='<?php echo Mage::getBaseUrl('js') ?>payment4b/payment4bwindow.js'></script>

<?php echo $this->getFormRedirect(); ?>
<center><br /><br />
<h3>
<?php echo $this->__('Al pinchar en continuar te derivaremos a la pasarela de pago de 4B, ning&uacute;n dato de la tarjeta se guarda en nuestros servidores, lo que hace los pagos 100% seguros.') ?>
</h3><br /><br />
<a href='<?php echo Mage::getUrl("payment4b/standard/visa/") ?>' target="_blank">
	<img src='<?php echo $this->getSkinUrl('images/payment4b/verifiedbyvisa.png') ?>' border="0" />
</a>&nbsp;&nbsp;
<a href='<?php echo Mage::getUrl("payment4b/standard/mastercard/")?>' target="_blank">
	<img src='<?php echo $this->getSkinUrl('images/payment4b/mastercard_secuercode.png') ?>' border="0" />
</a><br /><br /><br />
<input class="form-button" type="button" onclick="javascript:open_Payment4b_window();" value='<?php echo $this->__('Enviar') ?>' />

<br /><br /><br /><br />
</center>
