<table>
	<tr>
		<td><strong><?php echo $this->__("La misma tarjeta a&ntilde;ade m&aacute;s seguridad on-line.") ?></strong></td>
		<td>&nbsp;</td>
		<td><img src='<?php echo $this->getSkinUrl('images/payment4b/verifiedbyvisa.png') ?>' /></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__("Verified by Visa es un nuevo servicio que permite comprar on-line con una cofianza a&ntilde;adida.") ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3'><?php echo $this->__('Para activar Verified by Visa en su tarjeta Visa, o para m&aacute;s informaci&oacute;n, contacte con la entidad emisora de su tarjeta. <a href="http://www.visa.com/verified">visa.com/verified</a>.') ?></td>
	</tr>
	<tr>
		<td colspan='3'>&nbsp;</td>
	</tr>
	<tr>
		<td colspan='3' align='center'><button class='form-button' onclick='window.close()'><?php echo $this->__('Close Window') ?></button></td>
	</tr>
</table>
